# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='testquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='编号')),
                ('deleted', models.BooleanField(default=False, verbose_name='删除状态')),
            ],
            managers=[
                ('objects_undeleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
